name: Bot Dolar Peru

on:
  schedule:
    # Corre cada 10 minutos (*/10)
    # Desde las 14:00 UTC (9 AM Perú) hasta las 23:00 UTC (6 PM Perú)
    # De Lunes a Viernes
    - cron: '*/10 14-23 * * 1-5'
  workflow_dispatch:

# --- ESTO ES NUEVO Y CRUCIAL ---
permissions:
  contents: write  # Le da permiso al bot para guardar el archivo JSON
# -------------------------------

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: |
          pip install -r requirements.txt

      - name: Correr script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      # --- PASO EXTRA: GUARDAR MEMORIA ---
      - name: Guardar estado (Auto-Commit)
        run: |
          git config user.name "Bot Dolar Automatico"
          git config user.email "bot@github.com"
          git add estado.json
          # Solo hace commit si hubo cambios en el archivo
          git commit -m "Actualizando precio detectado" || exit 0
          git push
