name: Bot Dolar Peru

on:
  schedule:
    # CORREGIDO: De 14:00 UTC a 23:00 UTC (9 AM a 6 PM Perú)
    # Esto elimina el error de "Job not acquired"
    - cron: '*/10 14-23 * * 1-5'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          # CAMBIO OBLIGATORIO: Usamos 3.11 para arreglar el error de yfinance
          python-version: '3.11'

      - name: Instalar librerías
        run: |
          pip install -r requirements.txt

      - name: Correr script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      - name: Guardar estado (Auto-Commit)
        run: |
          git config user.name "Bot Dolar Automatico"
          git config user.email "bot@github.com"
          git add estado.json
          git commit -m "Actualizando precio detectado" || exit 0
          git push
